name: Update All Contributors
on:
  push:
    branches:
      - main
    paths:
      - .all-contributorsrc
      - README.md
      - README.zh-CN.md
  pull_request:
    branches:
      - main
    paths:
      - .all-contributorsrc
      - README.md
      - README.zh-CN.md

jobs:
  update-contributors:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install
      - name: Add Contributor
        run: node scripts/updateContributors.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}

      - name: Commit and Push Changes
        run: |
          git config --global user.email "ntscshen@163.com"
          git config --global user.name "ntscshen"
          git add .
          git commit -m "update contributors list"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
